const productVariations = [
  {
    productId: 1,
    variationName: "Styler",
    variationDescription: "The most stylish sneakers",
    price: 230,
    imageUrl: "/products/sneakers/styler-1.webp",
  },
  {
    productId: 1,
    variationName: "Jogger",
    variationDescription: "Sneakers for daily running",
    price: 270,
    imageUrl: "/products/sneakers/jogger-1.webp",
  },
  {
    productId: 1,
    variationName: "Sportman",
    variationDescription: "The true sport sneakers",
    price: 410,
    imageUrl: "/products/sneakers/sportman-1.webp",
  },
  {
    productId: 2,
    variationName: "Styler",
    variationDescription: "The most stylish sneakers",
    price: 180,
    imageUrl: "/products/sneakers/styler-2.webp",
  },
  {
    productId: 2,
    variationName: "Jogger",
    variationDescription: "Sneakers for daily running",
    price: 230,
    imageUrl: "/products/sneakers/jogger-2.webp",
  },
  {
    productId: 2,
    variationName: "Sportman",
    variationDescription: "The true sport sneakers",
    price: 375,
    imageUrl: "/products/sneakers/sportman-2.webp",
  },
  {
    productId: 3,
    variationName: "Styler",
    variationDescription: "The most stylish sneakers",
    price: 180,
    imageUrl: "/products/sneakers/styler-3.webp",
  },
  {
    productId: 3,
    variationName: "Jogger",
    variationDescription: "Sneakers for daily running",
    price: 230,
    imageUrl: "/products/sneakers/jogger-3.webp",
  },
  {
    productId: 3,
    variationName: "Sportman",
    variationDescription: "The true sport sneakers",
    price: 375,
    imageUrl: "/products/sneakers/sportman-3.webp",
  },
  {
    productId: 4,
    variationName: "Styler",
    variationDescription: "The most stylish sneakers",
    price: 180,
    imageUrl: "/products/sneakers/styler-4.webp",
  },
  {
    productId: 4,
    variationName: "Jogger",
    variationDescription: "Sneakers for daily running",
    price: 230,
    imageUrl: "/products/sneakers/jogger-4.webp",
  },
  {
    productId: 4,
    variationName: "Sportman",
    variationDescription: "The true sport sneakers",
    price: 375,
    imageUrl: "/products/sneakers/sportman-4.webp",
  },
  {
    productId: 5,
    variationName: "Styler",
    variationDescription: "The most stylish sneakers",
    price: 180,
    imageUrl: "/products/sneakers/styler-5.webp",
  },
  {
    productId: 5,
    variationName: "Jogger",
    variationDescription: "Sneakers for daily running",
    price: 230,
    imageUrl: "/products/sneakers/jogger-5.webp",
  },
  {
    productId: 5,
    variationName: "Sportman",
    variationDescription: "The true sport sneakers",
    price: 375,
    imageUrl: "/products/sneakers/sportman-5.webp",
  },
  {
    productId: 6,
    variationName: "Hand-styled T-shirt",
    variationDescription: "It was made with love",
    price: 65,
    imageUrl: "/products/t-shirts/hand-styled-tshirt-6.webp",
  },
  {
    productId: 7,
    variationName: "Customizable T-shirt",
    variationDescription: "You can customize it on your own",
    price: 100,
    imageUrl: "/products/t-shirts/customizable-tshirt-7.webp",
  },
  {
    productId: 8,
    variationName: "Posh T-shirt",
    variationDescription: "The winner of the fashion competition",
    price: 120,
    imageUrl: "/products/t-shirts/posh-tshirt-8.webp",
  },
  {
    productId: 8,
    variationName: "Styled T-shirt",
    variationDescription: "Slightly styled winner",
    price: 135,
    imageUrl: "/products/t-shirts/styled-tshirt-8.webp",
  },
  {
    productId: 9,
    variationName: "Common T-shirt",
    variationDescription: "Common t-shirt",
    price: 20,
    imageUrl: "/products/t-shirts/common-tshirt-9.webp",
  },
  {
    productId: 10,
    variationName: "Common T-shirt",
    variationDescription: "Common t-shirt",
    price: 15,
    imageUrl: "/products/t-shirts/common-tshirt-10.webp",
  },
  {
    productId: 11,
    variationName: "Classic Hoodie",
    variationDescription: "Warm and comfortable classic hoodie",
    price: 90,
    imageUrl: "/products/hoodies/classic-hoodie-11.webp",
  },
  {
    productId: 12,
    variationName: "Sport Hoodie",
    variationDescription: "Perfect for sporty activities",
    price: 110,
    imageUrl: "/products/hoodies/sport-hoodie-12.webp",
  },
  {
    productId: 13,
    variationName: "Casual Hoodie",
    variationDescription: "For casual wearing",
    price: 70,
    imageUrl: "/products/hoodies/casual-hoodie-13.webp",
  },
  {
    productId: 14,
    variationName: "Fancy Hoodie",
    variationDescription: "For people who want to stand out",
    price: 120,
    imageUrl: "/products/hoodies/fancy-hoodie-14.webp",
  },
  {
    productId: 15,
    variationName: "Glamorous Hoodie",
    variationDescription: "For people who want to shine",
    price: 150,
    imageUrl: "/products/hoodies/glamorous-hoodie-15.webp",
  },
  {
    productId: 16,
    variationName: "Designer Backpack",
    variationDescription: "Stylish and practical backpack",
    price: 150,
    imageUrl: "/products/backpacks/designer-backpack-16.webp",
  },
  {
    productId: 17,
    variationName: "Travel Backpack",
    variationDescription: "Ideal for travel and adventures",
    price: 180,
    imageUrl: "/products/backpacks/travel-backpack-17.webp",
  },
  {
    productId: 18,
    variationName: "Minimalist Backpack",
    variationDescription: "Simple and stylish backpack",
    price: 50,
    imageUrl: "/products/backpacks/minimalist-backpack-18.webp",
  },
  {
    productId: 19,
    variationName: "Fashion Backpack",
    variationDescription: "For fashion photography backpack",
    price: 70,
    imageUrl: "/products/backpacks/fashion-backpack-19.webp",
  },
  {
    productId: 20,
    variationName: "Studio Backpack",
    variationDescription: "Professional studio backpack",
    price: 100,
    imageUrl: "/products/backpacks/studio-backpack-20.webp",
  },
  {
    productId: 21,
    variationName: "Leather Jacket",
    variationDescription: "Sophisticated and stylish leather jacket",
    price: 250,
    imageUrl: "/products/jackets/leather-jacket-21.webp",
  },
  {
    productId: 22,
    variationName: "Bomber Jacket",
    variationDescription: "Trendy and comfortable bomber jacket",
    price: 200,
    imageUrl: "/products/jackets/bomber-jacket-22.webp",
  },
  {
    productId: 23,
    variationName: "Parka Jacket",
    variationDescription: "Waterproof and warm parka jacket",
    price: 300,
    imageUrl: "/products/jackets/parka-jacket-23.webp",
  },
  {
    productId: 24,
    variationName: "Denim Jacket",
    variationDescription: "Classic and stylish denim jacket",
    price: 120,
    imageUrl: "/products/jackets/denim-jacket-24.webp",
  },
  {
    productId: 25,
    variationName: "Trench Coat",
    variationDescription: "Elegant and timeless trench coat",
    price: 350,
    imageUrl: "/products/jackets/trench-coat-25.webp",
  },
];

export default productVariations;
